dist: trusty
language: csharp
mono: none
dotnet: 2.0.0
solution: Canducci.GraphQL.sln
install:
  - dotnet clean
script:    
  - dotnet restore -f netstandard2.0 Canducci.GraphQLQuery/Canducci.GraphQLQuery.csproj
  - dotnet restore -f netstandard2.0 Canducci.GraphQLQuery.CustomTypes/Canducci.GraphQLQuery.CustomTypes.csproj
  - dotnet restore -f netstandard2.0 Canducci.GraphQLQuery.MSTest/Canducci.GraphQLQuery.MSTest.csproj
  - dotnet restore -f netstandard2.0 Canducci.GraphQLQuery.CustomTypes.MSTest/Canducci.GraphQLQuery.CustomTypes.MSTest.csproj
  - dotnet build -f netstandard2.0 Canducci.GraphQLQuery/Canducci.GraphQLQuery.csproj
  - dotnet build -f netstandard2.0 Canducci.GraphQLQuery.CustomTypes/Canducci.GraphQLQuery.CustomTypes.csproj
  - dotnet test -f netcoreapp2.0 Canducci.GraphQLQuery.MSTest/Canducci.GraphQLQuery.MSTest.csproj
  - dotnet test -f netcoreapp2.0 Canducci.GraphQLQuery.CustomTypes.MSTest/Canducci.GraphQLQuery.CustomTypes.MSTest.csproj